### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by andresg747** [openhomeautomation/arduino-geofencing#1]
Hi,

I'm currently developing a monitor for elders based on your tutorial. It has helped me a lot!
I need to show a preview of the device to some teachers in a few days. 
One day ago the current version of the code (It´s all [here](https://github.com/andresg747/elder-monitor)) was working fine. I'm publishing data to adafruit.io, it's all public, you can check it out: https://io.adafruit.com/andresg747

But I've tried to connect today and I can not pass through the MQTT connection.

Debug log:

`Inicializando (puede tardar hasta 10 seg)
Attempting to open comm with ATs
---> AT
<--- OK
---> ATE0
<--- OK
---> ATE0
<--- OK
---> AT+CVHU=0
<--- OK
---> ATI
<--- SIM808 R14.18

OK

FONA Conectado!
Conectando a la red...
---> AT+CREG?
<--- +CREG: 0,1
Dehabilita GPRS
---> AT+CIPSHUT
<--- SHUT OK
---> AT+SAPBR=0,1
<--- OK
---> AT+CGATT=0
<--- OK
Habilita GPRS
---> AT+CIPSHUT
<--- SHUT OK
---> AT+CGATT=1
<--- OK
---> AT+SAPBR=3,1,"CONTYPE","GPRS"
<--- OK
---> AT+SAPBR=3,1,"APN","internet.movistar.ve"
<--- OK
---> AT+CSTT="internet.movistar.ve"
<--- OK
---> AT+SAPBR=1,1
<--- OK
---> AT+CIICR
<--- OK
Conectado a la red de datos.
Connecting to TCP
---> AT+CIPSHUT
<--- SHUT OK
---> AT+CIPMUX=0
<--- OK
---> AT+CIPRXGET=1
<--- OK
AT+CIPSTART="TCP","io.adafruit.com","1883"
<--- OK
<--- CONNECT OK
MQTT connect packet:
[0x10], : [0x3A], [0x00], [0x04], M [0x4D], Q [0x51], T [0x54], T [0x54],
[0x04], [0xC2], [0x01], , [0x2C], [0x00], [0x00], [0x00], [0x0A],
a [0x61], n [0x6E], d [0x64], r [0x72], e [0x65], s [0x73], g [0x67], 7 [0x37],
4 [0x34], 7 [0x37], [0x00], [0x20], 7 [0x37], 7 [0x37], 5 [0x35], d [0x64],
7 [0x37], b [0x62], c [0x63], f [0x66], c [0x63], 4 [0x34], 5 [0x35], 2 [0x32],
4 [0x34], 3 [0x33], 3 [0x33], 3 [0x33], b [0x62], 6 [0x36], 6 [0x36], 4 [0x34],
b [0x62], 9 [0x39], 4 [0x34], 1 [0x31], f [0x66], 3 [0x33], d [0x64], 8 [0x38],
2 [0x32], a [0x61], 1 [0x31], e [0x65],
Writing packet
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
AT+CIPSEND=60
0x10 0x3A 0x0 0x4 0x4D 0x51 0x54 0x54 0x4 0xFFFFFFC2 0x1 0x2C 0x0 0x0 0x0 0xA 0x61 0x6E 0x64 0x72 0x65 0x73 0x67 0x37 0x34 0x37 0x0 0x20 0x37 0x37 0x35 0x64 0x37 0x62 0x63 0x66 0x63 0x34 0x35 0x32 0x34 0x33 0x33 0x33 0x62 0x36 0x36 0x34 0x62 0x39 0x34 0x31 0x66 0x33 0x64 0x38 0x32 0x61 0x31 0x65
<--- >
<--- SEND OK
Reading data..
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
---> AT+CIPRXGET=4
<--- +CIPRXGET: 4,0
0 bytes available
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
Connection failed
No se pudo conectar a servidor MQTT...
`

I've used this service for almost two months already and it has been great so far. I don't know what's causing this error.

Any suggestions would be very appreciated. I need to solve this as soon as possible to present this to my teacher in a couple of days.

Thanks in advance!

**Comment by specialKody** [comment]
Hello andresg747,

Is there a way you could post the returned value from the _connectErrorString_ function? That value should print before "No se pudo conectar a servidor MQTT..." and it would help me trace the issue. Thanks!

-specialKody

**Comment by andresg747** [comment]
Here I am, searching through my opened issues and ran into this one. And replying almost three years later 😄

Thank you very much for your response. Fortunately I was able to solve the problem, and present this project successfully.

Unfortunately I don't remember what was the issue in the first place 😅

But thanks again for your awesome work with FONA.
